language: node_js
node_js:
  - 8.9
  - 9
script:
  - make ci
sudo: false
branches:
  except:
    - /^v\d/
before_deploy: yarn predeploy
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  fqdn: emdaer.me
  github_token: $DEPLOY_GH_TOKEN
  email: flipactual+emdaer@gmail.com
  name: emdaerbot
  on:
    branch: site
